[workspace]
resolver = "3"
members = ["./crates/*", "examples", "queued_signal"]


[workspace.dependencies]
dioxus_bevy_signals = {path = "crates/dioxus_bevy_signals", default-features = false}

dioxus = {version = "0.7.4", default-features = false}
dioxus-core = {version = "0.7.4"}
dioxus-signals = {version = "0.7.4"}
dioxus-document = {version = "0.7.4"}
dioxus-hooks = {version = "0.7.4"}
generational-box = {version = "0.7.4"}
dioxus-html = {version = "0.7.4"}
flume = {version = "0.12"}
anyhow = "1"
crossbeam-epoch = "0.9"
tokio = "1.51"
futures = "0.3"
parking_lot = "0.12.5"
# flashmap = "0.2"
bevy_ecs = {version = "0.17"}
bevy_app = {version = "0.17"}
bevy_asset = {version = "0.17"}
bevy_color = {version = "0.17"}
bevy_pbr = {version = "0.17"}
bevy_transform = {version = "0.17"}
bevy_time = {version = "0.17"}
bevy_log = {version = "0.17"}
tracing = { version = "0.1", default-features = false, features = ["std"] }
glam = {version = "0.30"}
trait-set = {version = "0.3"}
bytemuck = {version = "1.25", features = ["derive"]}
variadics_please = "1.1.0"
queued_signal = {path = "./queued_signal"}
left-right = "0.11.7"
cfg-if = "1.0"
macro-v = "0.1.4"
dioxus-native = "0.7"
blitz-shell = "0.2"
winit = "0.30"
parley = { version = "0.6", features = ["std"] }
tracing-subscriber = "0.3"
tracing-chrome = "0.7"

# [[example]]
# name = "minimal_dioxus"
# required-features = [""]
