[workspace]
resolver = "3"
members = ["./crates/*", "examples", "queued_signal", "crates/queued_signal_tracing"]


[workspace.dependencies]
dioxus_bevy_signals = {path = "crates/dioxus_bevy_signals", default-features = false}
queued_signal_tracing = { path = "crates/queued_signal_tracing" }

# dioxus = {git = "https://github.com/DioxusLabs/dioxus", rev = "b00ff7525901984f3a07fa5cfa175b537b64630b", default-features = false}
# dioxus-core = {git = "https://github.com/DioxusLabs/dioxus", rev = "b00ff7525901984f3a07fa5cfa175b537b64630b"}
# dioxus-signals = {git = "https://github.com/DioxusLabs/dioxus", rev = "b00ff7525901984f3a07fa5cfa175b537b64630b"}
# dioxus-document = {git = "https://github.com/DioxusLabs/dioxus", rev = "b00ff7525901984f3a07fa5cfa175b537b64630b"}
# dioxus-hooks = {git = "https://github.com/DioxusLabs/dioxus", rev = "b00ff7525901984f3a07fa5cfa175b537b64630b"}
# dioxus-native = {git = "https://github.com/DioxusLabs/dioxus", rev = "b00ff7525901984f3a07fa5cfa175b537b64630b"}
# dioxus-history = {git = "https://github.com/DioxusLabs/dioxus", rev = "b00ff7525901984f3a07fa5cfa175b537b64630b"}
# generational-box = {git = "https://github.com/DioxusLabs/dioxus", rev = "b00ff7525901984f3a07fa5cfa175b537b64630b"}
# dioxus-html = {git = "https://github.com/DioxusLabs/dioxus", rev = "b00ff7525901984f3a07fa5cfa175b537b64630b"}


dioxus = {path = "../dioxus/packages/dioxus", default-features = false}
dioxus-core = {path = "../dioxus/packages/core"}
dioxus-signals = {path = "../dioxus/packages/signals"}
dioxus-document = {path = "../dioxus/packages/document"}
dioxus-hooks = {path = "../dioxus/packages/hooks"}
dioxus-native = {path = "../dioxus/packages/native", default-features = false}
dioxus-history = {path = "../dioxus/packages/history"}
generational-box = {path = "../dioxus/packages/generational-box"}
dioxus-html = {path = "../dioxus/packages/html"}

flume = {version = "0.12"}
anyhow = "1"
tokio = "1.51"
parking_lot = "0.12.5"
# flashmap = "0.2"
bevy_ecs = {version = "0.19"}
bevy_app = {version = "0.19"}
bevy_asset = {version = "0.19"}
bevy_color = {version = "0.19"}
bevy_pbr = {version = "0.19"}
bevy_transform = {version = "0.19"}
bevy_time = {version = "0.19"}
bevy_log = {version = "0.19"}
tracing = { version = "0.1", default-features = false, features = ["std"] }
glam = {version = "0.32"}
trait-set = {version = "0.3"}
bytemuck = {version = "1.25", features = ["derive"]}
variadics_please = "1.1.0"
queued_signal = {path = "./queued_signal"}
left-right = "0.11.7"
cfg-if = "1.0"
macro-v = "0.1.4"

blitz-shell = { version = "=0.3.0-alpha.4", default-features = false }
blitz-traits = { version = "0.3.0-alpha.4", default-features = false }

winit = "0.31.0-beta.2"
parley = { version = "0.9", features = ["std"] }
tracing-subscriber = "0.3"
tracing-chrome = "0.7"

# [[example]]
# name = "minimal_dioxus"
# required-features = [""]
