[package]
name = "queued_signal"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = {version = "0.7.4", features = ["desktop"]}
dioxus-core = {version = "0.7.4"}
arc-swap = "1.9"
flume = {version = "0.12"}
tokio = "1.51"
flashmap = "0.2"
bevy_ecs = {version = "0.17"}
bevy_app = {version = "0.17"}
bytemuck = {version = "1.25", features = ["derive"]}