[package]
name = "bevy_signal_tests"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = {workspace = true}
bevy_ecs = {workspace = true, features = ["trace"]}
bevy_log = {workspace = true}
bevy_color = {workspace = true}
bevy_pbr = {workspace = true}
dioxus-core = {workspace = true}
bevy_asset = {workspace = true}
dioxus-hooks = {workspace = true}
dioxus-signals = {workspace = true}
dioxus = {workspace = true, features = ["lib"]}
flume = {workspace = true}
queued_signal = {workspace = true}
dioxus_bevy_signals = {workspace = true}
tokio = {workspace = true}
cfg-if = {workspace = true}

[features]
resource_tests = ["dioxus_bevy_signals/resource"]
query_tests = ["dioxus_bevy_signals/query"]
asset_tests = ["dioxus_bevy_signals/asset", "dioxus_bevy_signals/query"]
default = ["resource_tests", "query_tests", "asset_tests"]