[package]
name = "dioxus_bevy_signals"
version = "0.1.0"
edition = "2024"

[dependencies]
# todo, remove bevy_reflect post testing
bevy_ecs = {workspace = true}
bevy_app = {workspace = true}
bevy_asset = {workspace = true}
dioxus-core = {workspace = true}
dioxus = {workspace = true}
dioxus-hooks = {workspace = true}
dioxus-signals = {workspace = true}
bytemuck = {workspace = true}
generational-box = {workspace = true}
parking_lot = {workspace = true}
flume = {workspace = true}
queued_signal = {workspace = true}
trait-set = {workspace = true}
bevy_log = {workspace = true, optional = true}

[features]
asset = []
query = []
resource = []
tracing = ["bevy_log"]
default = ["asset", "query", "resource"]