[package]
name = "dioxus_bevy_signals"
version = "0.1.0"
edition = "2024"
description = "Mirror bevy state (resources, queries, assets) to dioxus via QueuedSignals"
repository = "https://github.com/rydb/queued_signal"
keywords = ["bevy", "dioxus", "signal", "ecs", "reactive"]
categories = ["game-engines", "gui"]
license = "Apache-2.0"

[dependencies]
bevy_ecs = {workspace = true}
bevy_app = {workspace = true}
bevy_asset = {workspace = true}
bevy_time = {workspace = true}
dioxus-core = {workspace = true}
dioxus = {workspace = true}
dioxus-hooks = {workspace = true}
dioxus-signals = {workspace = true}
bytemuck = {workspace = true}
generational-box = {workspace = true}
parking_lot = {workspace = true}
flume = {workspace = true}
tokio = {workspace = true}
queued_signal = {workspace = true}
trait-set = {workspace = true}
queued_signal_tracing = { workspace = true}
variadics_please = {workspace = true}
pastey = {workspace = true}

[features]
asset = []
query = []
resource = []
trace = ["queued_signal_tracing/trace"]
default = ["asset", "query", "resource"]