[package]
name = "bevy_signal_test"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = {workspace = true}
bevy_ecs = {workspace = true}
bevy_log = {workspace = true}
dioxus-core = {workspace = true}
dioxus-hooks = {workspace = true}
dioxus-signals = {workspace = true}
dioxus = {workspace = true}
flume = {workspace = true}
queued_signal = {workspace = true}
dioxus_bevy_signals = {workspace = true}
tokio = {workspace = true}