[package]
name = "queued_signal"
version = "0.1.0"
edition = "2024"
description = "A Dioxus signal for shared, wait-free reads and queued writes across VDOMs"
repository = "https://github.com/rydb/queued_signal"
keywords = ["dioxus", "signal", "state", "reactive"]
categories = ["gui", "concurrency"]
license = "Apache-2.0"


[dependencies]
dioxus = {workspace = true, features = ["macro", "hooks", "signals"]}
dioxus-signals = {workspace = true}
dioxus-core = {workspace = true}
dioxus-hooks = {workspace = true}

flume = {workspace = true}
tokio = {workspace = true, features = ["rt", "time", "sync", "macros"]}
variadics_please = {workspace = true}
left-right = {workspace = true}
parking_lot = {workspace = true}
anyhow = {workspace = true}
macro-v = {workspace = true}
queued_signal_tracing = { workspace = true }

[features]
trace = ["queued_signal_tracing/trace"]